Subscription implementation for pandora NewPendingHeaders event
lukso-network/lukso-orchestrator pull request #25
Opened 2021-05-04 14:28 UTC by atif-konasl

### What type of PR is this?

> feature

### What does this PR do? Why is it needed?

Subscribe to `eth_subscribe: params; [newPendingBlockHeaders, {fromBlockHash: blockHash}])` event in pandora client and gets new pending header. Headers are stored into cache and header hash with status are stored into cache and db.

### Which issues(s) does this PR fix?

Issue No - 
[https://github.com/lukso-network/lukso-orchestrator/issues/21](21)
[https://github.com/lukso-network/lukso-orchestrator/issues/23](23)

### Other notes for review

Simply run using the below command -
`./orchestrator --force-clear-db --ws --ws.addr=127.0.0.1 --ws.port=7878 --vanguard-rpc-endpoint=ws://34.91.105.59:8566 --pandora-rpc-endpoint=ws://34.91.105.59:8546 --verbosity=debug`

2021-05-11 12:08 UTC, blazejkrzak commented
We should test it @patred20 @atif-konasl get in touch

2021-05-14 12:29 UTC, blazejkrzak commented on orchestrator/db/kv/pandora_header_hash.go
> +func (s *Store) LatestSavedPandoraSlot() uint64 {
I think this function is missing short circuit
```go
// Quick return
	if s.latestPanHeaderHash != latestHeaderHash {
		return s.latestPanHeaderHash
	}
```

2021-05-14 12:30 UTC, blazejkrzak commented on orchestrator/db/kv/pandora_header_hash.go
> +func (s *Store) LatestSavedPandoraSlot() uint64 {
I was writing down tests for vanguard implementation and found it out

2021-05-14 12:33 UTC, blazejkrzak commented
Code looks good overall

2021-05-14 12:34 UTC, blazejkrzak requested changes
Consider short circuit.
Maybe I understand it wrong, then I'll accept the code review

2021-05-14 13:20 UTC, atif-konasl commented on orchestrator/db/kv/pandora_header_hash.go
> +func (s *Store) LatestSavedPandoraSlot() uint64 {
Thanks for finding out this.

2021-05-14 13:25 UTC, atif-konasl commented on orchestrator/db/kv/pandora_header_hash.go
> +func (s *Store) LatestSavedPandoraSlot() uint64 {
Yes we can but the thing is that, `LatestSavedPandoraSlot()` this method is only called when initialising the DB. So when db will be intialised, it should need to get last saved pandora header hash from db.

There is another method which provide you the latest header hash to outside of the `kv` package:
`func (s *Store) GetLatestHeaderHash() common.Hash {
	return s.latestPanHeaderHash
}`

2021-05-17 10:02 UTC, blazejkrzak commented
I suggest to introduce this changes before merge. This restores working go releaser
https://github.com/lukso-network/lukso-orchestrator/pull/29/commits/64e37150c41fbd103208b5d2ac6d93caffe8bbfa

2021-05-17 14:32 UTC, merged