[WIP] Feature/12/confirm block hashes
lukso-network/lukso-orchestrator pull request #39
Opened 2021-05-31 17:42 UTC by blazejkrzak

This changes should give response based on state in db
#12

2021-05-31 17:44 UTC, blazejkrzak commented on orchestrator/rpc/api/api_backend.go
> +	log.Info("I am starting to InvalidatePendingQueue by 50 batch elements")
this digit should not be static in log

2021-06-04 10:04 UTC, atif-konasl requested changes
`InvalidatePendingQueue` method flow:
1. get `LatestVerifiedRealmSlot` slot number from db
2. fetch pandora hashes from db from realmSlot
3. fetch vanguard hashes from db from realmSlot
4. then you check the length of the hashes
5. iterate vanguard hashes and for each slot number from realmSlot you check few things like:
    a. if pandora header hash and vanguard hash is nil, then you add this slot into a container which is called possibleInvalidPair
    b. if only pandora header is nil, then you mark the vanguard hash as pending and store it into possibleInvalidPair and store vanguard hash into db with pending status and continue the flow
    c. Same as b. Just you mark the pandora header hash as pending if vanguard hash is nill and store the pandora header hash into db with pending status and continue the flow
    d. if the above condition does not true then, then you store vanguard and pandora hash into db with verified status
    e. Then you save current slot number into db which is called `slotToCheck`, then save latest pandora and vanguard slot into db
    d. Then again your store pandora header hash and vanguard hash with status
6. Then you fetch `latestSavedVerifiedRealmSlot` from db
7. Then you iterate `possibleInvalidPair`
    a. if pair in `possibleInvalidPair` has future slot than `latestSavedVerifiedRealmSlot` then you just continue the flow
    b. if pair has slot which is previous than `latestSavedVerifiedRealmSlot` then you save the pandora and vanguard header hash into db with skipped status
    c. then you again retrieve the `latestSavedVerifiedRealmSlot` and check with pair slot number

So, In this implementation, you interact with db so many times in a single method:
    Total write operation: 11 times
    Total read operation: multiple times

IMHO, this implementation looks very inefficient to me. @Blaise#5532, @MattMar#0058 , @Anando#3349  we should discuss about this implementation.

2021-06-04 13:50 UTC, blazejkrzak commented on orchestrator/rpc/api/events/api.go
> +	go func() {
we need to have both, event and ticker based system

2021-06-04 13:50 UTC, blazejkrzak commented
Thank you for your comments @atif-konasl

2021-06-04 14:20 UTC, atif-konasl commented on orchestrator/rpc/api/events/api.go
> +	go func() {
Sorry i can not find any motivation to use ticker based system. Could you please explain?

2021-06-17 04:58 UTC, atif-konasl approved these changes
@blazejkrzak IMHO this implementation looks very complex and resource intensive. You have used 10+ go routines and many db calls for solving this issue whereas we could solve this issue with 1 or 2 go routines and less db calls. I think, we need to refactor this implementation in future. 

For now this implementation is OK for me. After finishing our all implementation we must need to refactor this implementation.

2021-06-17 19:56 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	service.workLoop()
It surely can be that way

2021-06-17 19:57 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	stopChan                    chan bool
Isnt a struct less primitive than bool?

2021-06-17 20:00 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	service.stopChan <- true
I think you are wrong. Your sugestion will close the channel not send signal to the receiver that should stop

2021-06-17 20:00 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	return nil
I think it was needed by service registry interface

2021-06-17 20:01 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	stopChan := make(chan bool)
Same here, I think that struct is less primitive than bool

2021-06-17 20:02 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +		if stop {
You can have the same logic that you handle any signal that came to that channel and just stop but that was intenional to stop only on bool true

2021-06-17 20:02 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +		if shouldSkip {
Motivation here is to be strict

2021-06-17 20:07 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	go func() {
yes, its redundant, its leftover. Good catch

2021-06-17 20:07 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	go func() {
- [ ] remove redundant log function

2021-06-17 20:08 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	service.workLoop()
- [ ] make routine outside the function body

2021-06-17 20:11 UTC, blazejkrzak commented on orchestrator/node/node.go
> +	go func() {
We need, look below. We have debouncers there. You can aggregate routines and this was the purpose. If you do not do goroutine than it will never reach line 297

2021-06-17 21:07 UTC, blazejkrzak commented
> @blazejkrzak IMHO this implementation looks very complex and resource intensive. You have used 10+ go routines and many db calls for solving this issue whereas we could solve this issue with 1 or 2 go routines and less db calls. I think, we need to refactor this implementation in future.
> 
> For now this implementation is OK for me. After finishing our all implementation we must need to refactor this implementation.

I would love to know how to do it with 1 or 2 routines

2021-06-18 07:36 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	go func() {
Hmm. On a second thought I see that debouncer is used so having goroutines inside function is IMHO good idea

2021-06-18 07:37 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +	go func() {
Altough you could provide me code sample how you image it and maybe I'll get another view

2021-06-18 12:19 UTC, atif-konasl commented on orchestrator/consensus/service.go
> +func invokeInvalidation(
I think we do not need any crawler. lets say pandora and vanguard sends block header of slot #5 and in orchestrator there is a slot 4 which is in pending status(According to your assumption say slot #4 comes later after slot #5 in `orchestrator`) and latestVerifiedSlot is 3. So your `invokeInvalidation` method pull slot #4 and slot #5 from db and send it to `crawler` and `crawler` invalidates these 2 slots and changes status pending to verified in `orchestrator` db. But please think about in vanguard and pandora side, do they re-process the block for slot #4? The time frame for slot #4 has been already passed and `van` and `pan` has already skipped that slot because in that time orchestrator did not send verified status. It's all about timing.

Now the slot status for slot #4 in orchestrator will be verified but in van and pan client, they skipped that slot #4. How do we solve this scenario based on your crawler based solution?

2021-06-19 18:37 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +func invokeInvalidation(
Its your decision to skip those slots, why did you implement it at first place?
Pandora and vanguard are faulty, not orchestrator

2021-06-19 18:39 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +func invokeInvalidation(
you have fixed yourself with edge scenario that is coming from faulty implementation from pandora and vanguard and you are trying to convince me that solution that works, is tested on every possible layer and on dev environment is not needed. I don't buy it. Its not about criticism, its starting to being a bit annoying

2021-06-21 10:52 UTC, blazejkrzak commented on orchestrator/pandorachain/handler.go
> +	latestRealmVerifiedSlot := s.db.LatestVerifiedRealmSlot()
This will fix/restrict your scenario @atif-konasl

2021-06-21 10:53 UTC, blazejkrzak commented on orchestrator/vanguardchain/handler.go
> +	latestRealmVerifiedSlot := s.orchestratorDB.LatestVerifiedRealmSlot()
this will restrict/prevent your scenario @atif-konasl

2021-06-21 10:54 UTC, blazejkrzak commented on orchestrator/consensus/service.go
> +func invokeInvalidation(
This changes will prevent any changes when reorg happens

https://github.com/lukso-network/lukso-orchestrator/pull/39#pullrequestreview-688288545
https://github.com/lukso-network/lukso-orchestrator/pull/39#pullrequestreview-688289054

2021-06-24 14:33 UTC, blazejkrzak commented
On top of this changes setup works:
```yaml
Any new changes on top of this setup should behave almost the same and not be regressive.
Staging:
- VANGUARD_GH_TAG: v0.0.14-zeta
- PANDORA_GH_TAG: p-v0.0.10-alpha-interval-gh-actions
- ORCHESTRATOR_GH_TAG: v0.0.24-alpha
```
![Screenshot from 2021-06-24 16-22-58](https://user-images.githubusercontent.com/26545969/123281295-dd59bd80-d509-11eb-92dd-0411168e0156.png)
![Screenshot from 2021-06-24 16-22-23](https://user-images.githubusercontent.com/26545969/123281300-de8aea80-d509-11eb-9424-2a316aa7a990.png)

2021-06-25 08:10 UTC, merged